# One hot encoding and Dummy variables

In [114]:
import pandas as pd
import numpy as np


In [115]:
df = pd.read_csv("homeprices.csv")
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [116]:
dummies = pd.get_dummies(df.town)
dummies.head()

monroe township  robinsville  west windsor
0                1            0             0
1                1            0             0
2                1            0             0
3                1            0             0
4                1            0             0

In [117]:
df_with_dummies = pd.concat([df, dummies], axis = 'columns')
df_with_dummies.head()

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [118]:
##Muliticore dummy variable problem is there: so we want to drop one of dummy variable. I drop west windsor

final = df_with_dummies.drop(['town','west windsor'], axis = 'columns')
final.head()

area   price  monroe township  robinsville
0  2600  550000                1            0
1  3000  565000                1            0
2  3200  610000                1            0
3  3600  680000                1            0
4  4000  725000                1            0

In [119]:
from sklearn.linear_model import LinearRegression 
model = LinearRegression()

In [120]:
X = final.drop(['price'],axis = 'columns') #Droppinf the dependant variable
X.head()

area  monroe township  robinsville
0  2600                1            0
1  3000                1            0
2  3200                1            0
3  3600                1            0
4  4000                1            0

In [121]:
Y = final.price
Y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [122]:
model.fit(X,Y)

LinearRegression()

In [123]:
model.predict([[28800,1,0]]) ## Predicting the price

array([3864422.7047942])

In [124]:
model.score(X,Y)

0.9573929037221873

In [125]:
from sklearn.preprocessing import LabelEncoder ##Using sklearn one hot encoder
le = LabelEncoder()

In [126]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [127]:
X = df[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [128]:
Y = dfle.price

In [134]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories = [])

In [135]:
X = ohe.fit_transform(X).toarray()

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [131]:
X = X[:,1:]
X

array([[2600],
       [3000],
       [3200],
       [3600],
       [4000],
       [2600],
       [2800],
       [3300],
       [3600],
       [2600],
       [2900],
       [3100],
       [3600]], dtype=int64)

In [132]:
model.fit(X,Y)

LinearRegression()

In [133]:
model.predict([[]])

array([257293.21717486])